### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by PalePyth** [gigabit101/NEIlootbags#2]
NEI lootbags isn't compatible with GregTech.

It shows things from GregTech like null tiny dust. And it shows that for everything. It also shows a lootbag as way to get everything (at least for me), try the bedrock or the command block.

**Comment by gigabit101** [comment]
It is just getting a ItemStack with meta.
So this is not my problem

**Comment by PalePyth** [comment]
Oh sorry. I mean this: (clicking bedrock)

http://puu.sh/psGHl/6594af4f45.jpg
http://puu.sh/psGIw/cf59e9d1d0.png

**Comment by gigabit101** [comment]
o0 thats a very old version update

**Comment by gigabit101** [comment]
yeah the new gui looks like this http://minecraft.curseforge.com/projects/neilootbags

**Comment by gigabit101** [comment]
also I have not released a 2.0.4 so I don't know what that version is so...

**Comment by gigabit101** [comment]
never mind was looking a lootbags not NEI lootbags

**Comment by PalePyth** [comment]
Anyway now it works thanks for your patience :)

**Comment by gigabit101** [comment]
np
